spring
BondarenkoJek/SpringDemo pull request #1
Opened 2019-02-04 13:07 UTC by BondarenkoJek

2019-02-04 13:38 UTC, DmitriyLitvin requested changes

2019-02-04 13:38 UTC, Dimitriy1 commented on src/main/webapp/resources/styles/registration.css
> +}
empty line should be here

2019-02-04 13:38 UTC, Dimitriy1 commented on src/main/webapp/resources/styles/login.css
> +}
empty line should be here

2019-02-04 13:38 UTC, Dimitriy1 commented on src/main/webapp/WEB-INF/pages/registration.jsp
> +
I ain't good at html css, but I think that empty lines between tags should have been deleted by you

2019-02-04 13:38 UTC, Dimitriy1 commented on src/main/webapp/WEB-INF/pages/login.jsp
>  </html>
empty line

2019-02-04 13:38 UTC, Dimitriy1 commented on src/main/webapp/WEB-INF/pages/login.jsp
>  </html>
shoud be added here

2019-02-04 13:38 UTC, Dimitriy1 commented on src/main/resources/log4j2.xml
>  </Configuration>
empty line shoud be added here

2019-02-04 13:38 UTC, Dimitriy1 commented on src/main/resources/db.properties
>  password=root
empty line shoud be added here

2019-02-04 13:38 UTC, Dimitriy1 commented on src/main/java/ua/bondarenkojek/util/log4j2.xml
> +</Configuration>
empty line shoud be added here

2019-02-04 13:38 UTC, Dimitriy1 commented on src/main/webapp/WEB-INF/pages/login.jsp
>  </html>
Strange situation, but css styles had been usless with tag - link untlil I used constraction <style><%@include file='path' %></style> where path - path to your file. So If It works - good, but check it please

2019-02-04 19:35 UTC, DmitriyLitvin approved these changes

2019-02-05 11:29 UTC, boroda4436 approved these changes
LGTM

2019-02-11 09:50 UTC, merged